# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'OgreSpace' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
 use_frameworks!

  # Pods for OgreSpace

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'TextFieldEffects'
  pod 'MaterialTextField', '~> 0.2'
  pod 'SkyFloatingLabelTextField'
  pod 'IQKeyboardManagerSwift'
  pod 'Toast-Swift'
  pod 'JWTDecode'
  pod 'BSImagePicker'
  pod 'SDWebImage', '~> 4.2.3'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'GoogleSignIn'
  pod 'Charts'
#  pod 'DTPhotoViewerController'
  pod 'SKPhotoBrowser'
  pod 'Hero'


end
